"""Adding composite indexing for (user_id and book_id)

Revision ID: 6488c75462f6
Revises: b8a61fba5eef
Create Date: 2025-06-02 23:54:14.378935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6488c75462f6'
down_revision: Union[str, None] = 'b8a61fba5eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_book', 'rating', ['user_id', 'book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_book', table_name='rating')
    # ### end Alembic commands ###
