"""Adding UniqueConstraints to (title,author) in book table

Revision ID: 9c68e2bf82a7
Revises: 6488c75462f6
Create Date: 2025-06-03 00:55:24.928620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c68e2bf82a7'
down_revision: Union[str, None] = '6488c75462f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_title_autror', 'book', ['title', 'author'], unique=False)
    op.create_unique_constraint('unique_book_title_author', 'book', ['title', 'author'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_book_title_author', 'book', type_='unique')
    op.drop_index('idx_title_autror', table_name='book')
    # ### end Alembic commands ###
