"""Adding unique constraint for a composite key (book_id, user_id)

Revision ID: b8a61fba5eef
Revises: fb625590cca0
Create Date: 2025-06-02 23:46:01.345356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a61fba5eef'
down_revision: Union[str, None] = 'fb625590cca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_book_user_rating', 'rating', ['book_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_book_user_rating', 'rating', type_='unique')
    # ### end Alembic commands ###
