"""Indexing title and author fields.

Revision ID: d0d0677e9044
Revises: 9c68e2bf82a7
Create Date: 2025-06-03 17:33:40.755187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d0677e9044'
down_revision: Union[str, None] = '9c68e2bf82a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_author', 'book', ['author'], unique=False)
    op.create_index('idx_title', 'book', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_title', table_name='book')
    op.drop_index('idx_author', table_name='book')
    # ### end Alembic commands ###
