"""Updating type of rating value field

Revision ID: fb625590cca0
Revises: 65b4a8ab1193
Create Date: 2025-06-02 23:38:20.787291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb625590cca0'
down_revision: Union[str, None] = '65b4a8ab1193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating', 'value',
               existing_type=sa.NUMERIC(precision=1, scale=0),
               type_=sa.Numeric(precision=2, scale=1),
               existing_nullable=False)
    op.create_unique_constraint(None, 'rating', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating', type_='unique')
    op.alter_column('rating', 'value',
               existing_type=sa.Numeric(precision=2, scale=1),
               type_=sa.NUMERIC(precision=1, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###
